services:
  frontend:
    build:
      context: .
    container_name: members_card
    ports:
      - "8000:80"
    volumes:
      - ./members_card/static:/home/www-data/app/static:ro
      - ./members_card/api:/home/www-data/app/api:ro
      - ./members_card/frontend:/home/www-data/app/frontend:ro
      - ./members_card/members_card:/home/www-data/app/members_card:ro
      - ./members_card/templates:/home/www-data/app/templates:ro
    environment:
      - NAME='Room Booking' # Pretty Name
      - APPNAME=members_card # Django project name. The folder name that contains the wsgi.py file.
      # - DESC=
      - PROJECTPATH=/home/www-data/app
      # - PYTHONPATH=/home/www-data/app/.venv/bin # Path to python install.
      # - CONFFILE=/etc/gunicorn/gunicorn.conf.py # Path to gunicorn configuration file.
      # - GUNICORN_BIND='["unix:/tmp/gunicorn.sock"]' # Bind address for Gunicorn. *NOTE* change the nginx.conf file to match. 
      - PIDFILE=/tmp/gunicorn.pid
    restart: unless-stopped

