# Generated by Django 4.2.5 on 2023-10-02 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberCard",
            fields=[
                (
                    "card_num",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Card Number"
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                (
                    "issued_date",
                    models.DateField(auto_now_add=True, verbose_name="Issued on"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        default=datetime.date(2024, 10, 1), verbose_name="Expires on"
                    ),
                ),
            ],
        ),
    ]
